### ISSUE TITLE
iHealth SDK documentation is lacking...

### ISSUE THREAD

**Issue by famesjranko** [iHealthLabs/Android-SDK#4]
I've bought multiple devices with the plan to build a self-hosted app for them for myself, but the documentation on your main website - and apparently here too - is lacking.

The reason I purchased your devices was the self-described openness to active development with your platform, however, I haven't seen that to be the case in practice.

Are these repositories still being monitored for activity?  If so, could someone from your development team reach out to me here and if possible provide resources for working with the purchased devices.

**Comment by jzhw0130** [comment]
##Attentation：The current repository will not update, please contact: [lichao@ihealthlabs.com.cn](mailto:lichao@ihealthlabs.com.cn)
